import os
import json

json_output_path = "output/exported_data.json"

def intermediate_export():

    # Save filtered datasets based on user-selected categories, channels, or trending periods.
    pass


def advanced_export():
    # Export recommendations generated by the system for a selected

    # video, including similar videos based on categories and tags.

    # Save anomaly detection results, including flagged videos with unusual engagement patterns, in a structured JSON report.

    # Export predictive trending duration results for videos, allowing further analysis or integration with other systems.
    pass

# export data to csv


def export_data_csv(data):
    if not os.path.exists("output/exports"):
        os.makedirs("output/exports")

        if not data:
            print("No data to export.")

    print("exporting data as csv...")

    # export data to json


def export_data_json(data):
    if not os.path.exists("output/exports"):
        os.makedirs("output/exports")

    if not data:
        print("No data to export.")
        input("Press Enter to return to the main menu...")
        return

    output_path = "output/exports/exported_data.json"

    try:
        with open(output_path, "w", encoding="utf-8") as file:
            json.dump(data, file, indent=4)

        print(f"SUCCESS: Data exported to {output_path}")

    except Exception as e:
        print(f"ERROR exporting data: {e}")

    input("Press Enter to return to the main menu...\n")
    

# Save a list of the top 10 trending videos, including views, likes, and comments, in CSV or JSON format.
def top_10_trending_videos(loaded_data):
    if not os.path.exists("output/exports"):
        os.makedirs("output/exports")

    if not loaded_data:
        print("No data to export.")
        input("Press Enter to return...")
        return

    output_path = "output/exports/top_10_trending_videos.json"

    # Sort by views (descending)
    sorted_videos = sorted(
        loaded_data,
        key=lambda x: int(x["views"]),
        reverse=True
    )

    top_10 = []

    for video in sorted_videos[:10]:
        top_10.append({
            "video_id": video["video_id"],
            "title": video["title"],
            "channel_title": video["channel_title"],
            "views": video["views"],
            "likes": video["likes"],
            "comment_count": video["comment_count"]
        })

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(top_10, f, indent=4, ensure_ascii=False)

    print(f"\nTop 10 trending videos exported to {output_path}")
    input("Press Enter to return...")


def selected_video_details(loaded_data):
    # Export detailed information for a selected video in JSON format.
    # Ensure export directory exists
    if not os.path.exists("output/exports"):
        os.makedirs("output/exports")

    if not loaded_data:
        print("No data to export.")
        input("Press Enter to return...")
        return

    video_id = input("Enter a video id: ").strip()
    output_path = f"output/exports/{video_id}_video_details.json"

    # Find the video
    for row in loaded_data:
        if row["video_id"] == video_id:
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(row, f, indent=4, ensure_ascii=False)

            print(f"\nVideo data exported successfully to {output_path}")
            input("Press Enter to return...")
            return

    # If not found
    print("Video ID not found. Nothing was exported.")
    input("Press Enter to return...")

# Export aggregated engagement metrics per category(averages, totals) in JSON format.


def export_category_metrics(loaded_data):
    # Ensure export directory exists
    if not os.path.exists("output/exports"):
        os.makedirs("output/exports")

    if not loaded_data:
        print("No data to export.")
        input("Press Enter to return...")
        return

    output_path = "output/exports/category_engagement_metrics.json"

    category_metrics = {}

    # Aggregate totals per category
    for row in loaded_data:
        cid = row["category_id"]

        if cid not in category_metrics:
            category_metrics[cid] = {
                "video_count": 0,
                "total_views": 0,
                "total_likes": 0,
                "total_comments": 0
            }

        category_metrics[cid]["video_count"] += 1
        category_metrics[cid]["total_views"] += int(row["views"])
        category_metrics[cid]["total_likes"] += int(row["likes"])
        category_metrics[cid]["total_comments"] += int(row["comment_count"])

    # Compute averages
    for cid, data in category_metrics.items():
        count = data["video_count"]
        data["avg_views"] = data["total_views"] / count
        data["avg_likes"] = data["total_likes"] / count
        data["avg_comments"] = data["total_comments"] / count

    # Export to JSON
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(category_metrics, f, indent=4)

    print(f"\nCategory engagement metrics exported to {output_path}")
    input("Press Enter to return...")
    
# Save filtered datasets based on user-selected categories, channels, or trending periods.
def filter_by_category(loaded_data):
    print("Filter by category")

    if not loaded_data:
        print("No data available.")
        input("Press Enter to return...")
        return

    category_id = input("Enter category ID: ").strip()

    filtered = [row for row in loaded_data if row["category_id"] == category_id]

    if not filtered:
        print("No videos found for this category.")
        input("Press Enter to return...")
        return

    os.makedirs("output/exports", exist_ok=True)
    output_path = f"output/exports/category_{category_id}_filtered.json"

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(filtered, f, indent=4, ensure_ascii=False)

    print(f"Filtered data exported to {output_path}")
    input("Press Enter to return...")


def filter_by_channel(loaded_data):
    print("Filter by channel")

    if not loaded_data:
        print("No data available.")
        input("Press Enter to return...")
        return

    channel_title = input("Enter channel title: ").strip()

    filtered = [
        row for row in loaded_data
        if row["channel_title"].lower() == channel_title.lower()
    ]

    if not filtered:
        print("No videos found for this channel.")
        input("Press Enter to return...")
        return

    os.makedirs("output/exports", exist_ok=True)
    output_path = "output/exports/channel_filtered.json"

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(filtered, f, indent=4, ensure_ascii=False)

    print(f"Filtered data exported to {output_path}")
    input("Press Enter to return...")


def filter_by_trending_period(loaded_data):
    print("Filter by trending period")

    if not loaded_data:
        print("No data available.")
        input("Press Enter to return...")
        return

    trending_date = input("Enter trending date (YY.DD.MM): ").strip()

    filtered = [
        row for row in loaded_data
        if row["trending_date"] == trending_date
    ]

    if not filtered:
        print("No videos found for this trending period.")
        input("Press Enter to return...")
        return

    os.makedirs("output/exports", exist_ok=True)
    output_path = f"output/exports/trending_{trending_date}_filtered.json"

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(filtered, f, indent=4, ensure_ascii=False)

    print(f"Filtered data exported to {output_path}")
    input("Press Enter to return...")
